#!/usr/bin/bash


#VPCID = $(aws ec2 create-vpc --cidr-block 10.10.0.0/16 \
#       --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=AWSCookbook201}]' \
#       --output text --query Vpc.VpcId)
#


VPCID="vpc-077ae3f5e1a7e16cd" 
echo "Creating VPC 9: $VPCID"


function delay(){  
        
        run=1

        while [run = 1]
        do

        status=$(aws ec2 describe-vpcs --vpc-ids $VPCID | jq -r '.Vpcs[].State')

                if [ "$status" = "available" ]; then
                        test="true"
                        run=0

                else
                        test="false"
                        echo $status
                        printf("VPC not ready yet scrip will sleep for 2 seconds\n")
                        sleep 2
                        
                fi
        done
        
        echo $status
}

echo $status
echo $test

echo "task2"
sleep 3

echo "task3"
sleep 3
